# Stage 1: Build the application
FROM node:22 AS build

# Set the working directory
WORKDIR /app

# Copy only necessary files for dependency installation
COPY package*.json ./

# Install dependencies
RUN npm ci

# Copy the rest of the application files (e.g., source, Prisma schema)
COPY . .

# Generate Prisma client for the correct binary targets
RUN npx prisma generate

# Stage 2: Production image
FROM node:22 AS production

# Set the working directory
WORKDIR /app

# Copy all the application files
COPY . .

# Run development server
CMD ["npm", "run", "dev"]